@startuml

abstract IFeature {
  +get_attribute_name(): str
  +get_value(): Union[str, int, float, bool]
}

abstract IRule {
  +execute(features: List[Type[IFeature]]): void
  +get_result(): Union[float, int, bool]
}

abstract IController {
  +get_features(): List[Type[IFeature]]
  +get_rules(): List[Type[IRule]]
  +get_fraud_score():int
  +execute_logic(): int
  +final execute():str
  +preExecute():bool
  +postExecute():str
}


@enduml
